services:
  mongo:
    image: mongo:6
    container_name: fittrack-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fittrack-net

  backend:
    build: ./backend
    container_name: fittrack-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=supersecretfittrackjwtkey
      - MONGO_URI=mongodb://mongo:27017/fittrack
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - fittrack-net

  frontend:
    build: ./frontend
    container_name: fittrack-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - fittrack-net

volumes:
  mongo-data:

networks:
  fittrack-net:
    driver: bridge
